spring:
  application:    name: rifaria-api
  h2:
    console:      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
  
server:
  port: 8088
  servlet:
    context-path: /api/v1